from __future__ import annotations
import collections.abc
import oead
import typing
import typing_extensions
__all__: list[str] = ['Amta', 'AssetType', 'Bars', 'ChannelInfo', 'DspAdpcmInfo', 'DspAdpcmLoopParam', 'DspAdpcmParam', 'ExtEntry', 'FileWithMetadata', 'Fstm', 'Fstp', 'Fwav', 'IAssetFile', 'MarkerInfo', 'PrefetchData', 'PrefetchDataBlock', 'SampleFormat', 'SoundFileHeader', 'StreamInfoBlock', 'StreamRegionInfo', 'StreamSeekInfo', 'StreamSoundInfo', 'StreamTrack', 'StreamTrackInfo', 'WaveInfo']
class Amta:
    asset_name: str
    endian: oead.Endianness
    type: AssetType
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing_extensions.Buffer) -> None:
        ...
    def get_ext_entry(self, idx: typing.SupportsInt | typing.SupportsIndex) -> ExtEntry:
        ...
    def get_marker(self, idx: typing.SupportsInt | typing.SupportsIndex) -> MarkerInfo:
        ...
    def get_stream_track(self, idx: typing.SupportsInt | typing.SupportsIndex) -> StreamTrack:
        ...
    def set_ext_entry(self, ext: ExtEntry, idx: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_marker(self, marker: MarkerInfo, idx: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_stream_track(self, track: StreamTrack, idx: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def to_binary(self) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self, endian: oead.Endianness) -> oead.Bytes:
        ...
    @property
    def amplitude_peak(self) -> float:
        ...
    @amplitude_peak.setter
    def amplitude_peak(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def channel_count(self) -> int:
        ...
    @channel_count.setter
    def channel_count(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def ext_entries(self) -> list[ExtEntry]:
        ...
    @ext_entries.setter
    def ext_entries(self, arg1: collections.abc.Sequence[ExtEntry]) -> None:
        ...
    @property
    def flags(self) -> int:
        ...
    @flags.setter
    def flags(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_end_frame(self) -> int:
        ...
    @loop_end_frame.setter
    def loop_end_frame(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_start_frame(self) -> int:
        ...
    @loop_start_frame.setter
    def loop_start_frame(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def markers(self) -> list[MarkerInfo]:
        ...
    @markers.setter
    def markers(self, arg1: collections.abc.Sequence[MarkerInfo]) -> None:
        ...
    @property
    def sample_count(self) -> int:
        ...
    @sample_count.setter
    def sample_count(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sample_rate(self) -> int:
        ...
    @sample_rate.setter
    def sample_rate(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def stream_tracks(self) -> typing.Annotated[list[StreamTrack], "FixedSize(8)"]:
        ...
    @stream_tracks.setter
    def stream_tracks(self, arg1: typing.Annotated[collections.abc.Sequence[StreamTrack], "FixedSize(8)"]) -> None:
        ...
    @property
    def unknown(self) -> float:
        ...
    @unknown.setter
    def unknown(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def used_stream_tracks(self) -> int:
        ...
    @used_stream_tracks.setter
    def used_stream_tracks(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def version(self) -> int:
        ...
    @version.setter
    def version(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def volume(self) -> float:
        ...
    @volume.setter
    def volume(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class AssetType:
    """
    Members:
    
      Wave
    
      Stream
    
      Unknown
    """
    Stream: typing.ClassVar[AssetType]  # value = <AssetType.Stream: 1>
    Unknown: typing.ClassVar[AssetType]  # value = <AssetType.Unknown: 2>
    Wave: typing.ClassVar[AssetType]  # value = <AssetType.Wave: 0>
    __members__: typing.ClassVar[dict[str, AssetType]]  # value = {'Wave': <AssetType.Wave: 0>, 'Stream': <AssetType.Stream: 1>, 'Unknown': <AssetType.Unknown: 2>}
    @typing.overload
    def __eq__(self, other: AssetType) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: AssetType) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Bars:
    endian: oead.Endianness
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing_extensions.Buffer) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    def add_file(self, meta: Amta, file: IAssetFile) -> None:
        ...
    @typing.overload
    def file_to_binary(self, idx: typing.SupportsInt | typing.SupportsIndex) -> oead.Bytes:
        ...
    @typing.overload
    def file_to_binary(self, arg0: str) -> oead.Bytes:
        """
        name
        """
    @typing.overload
    def get_file(self, idx: typing.SupportsInt | typing.SupportsIndex) -> FileWithMetadata:
        ...
    @typing.overload
    def get_file(self, name: str) -> FileWithMetadata:
        ...
    @typing.overload
    def meta_to_binary(self, idx: typing.SupportsInt | typing.SupportsIndex) -> oead.Bytes:
        ...
    @typing.overload
    def meta_to_binary(self, name: str) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self, endian: oead.Endianness) -> oead.Bytes:
        ...
    @property
    def files(self) -> list[FileWithMetadata]:
        ...
    @files.setter
    def files(self, arg1: collections.abc.Sequence[FileWithMetadata]) -> None:
        ...
    @property
    def version(self) -> int:
        ...
    @version.setter
    def version(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class ChannelInfo:
    adpcm_info: DspAdpcmInfo
    def __init__(self) -> None:
        ...
class DspAdpcmInfo:
    loop_param: DspAdpcmLoopParam
    param: DspAdpcmParam
class DspAdpcmLoopParam:
    @property
    def loop_predictor_scale(self) -> int:
        ...
    @loop_predictor_scale.setter
    def loop_predictor_scale(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_yn1(self) -> int:
        ...
    @loop_yn1.setter
    def loop_yn1(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_yn2(self) -> int:
        ...
    @loop_yn2.setter
    def loop_yn2(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class DspAdpcmParam:
    @property
    def coefficients(self) -> typing.Annotated[list[typing.Annotated[list[int], "FixedSize(2)"]], "FixedSize(8)"]:
        ...
    @coefficients.setter
    def coefficients(self, arg0: typing.Annotated[collections.abc.Sequence[typing.Annotated[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], "FixedSize(2)"]], "FixedSize(8)"]) -> None:
        ...
    @property
    def predictor_scale(self) -> int:
        ...
    @predictor_scale.setter
    def predictor_scale(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def yn1(self) -> int:
        ...
    @yn1.setter
    def yn1(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def yn2(self) -> int:
        ...
    @yn2.setter
    def yn2(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class ExtEntry:
    name: str
    @property
    def value(self) -> int:
        ...
    @value.setter
    def value(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class FileWithMetadata:
    asset: IAssetFile
    meta: Amta
class Fstm:
    endian: oead.Endianness
    info: StreamInfoBlock
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing_extensions.Buffer) -> None:
        ...
    def get_region_info(self, id: typing.SupportsInt | typing.SupportsIndex) -> StreamRegionInfo:
        ...
    def get_seek_info(self, block: typing.SupportsInt | typing.SupportsIndex, channel: typing.SupportsInt | typing.SupportsIndex) -> StreamSeekInfo:
        ...
    def has_region(self) -> bool:
        ...
    def set_region_info(self, info: StreamRegionInfo, id: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_seek_info(self, info: StreamSeekInfo, block: typing.SupportsInt | typing.SupportsIndex, channel: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def to_binary(self) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self, endian: oead.Endianness) -> oead.Bytes:
        ...
    @property
    def region_infos(self) -> list[StreamRegionInfo]:
        ...
    @region_infos.setter
    def region_infos(self, arg1: collections.abc.Sequence[StreamRegionInfo]) -> None:
        ...
    @property
    def samples(self) -> list[list[int | int | int | int]]:
        ...
    @samples.setter
    def samples(self, arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
    @property
    def seek_infos(self) -> list[list[StreamSeekInfo]]:
        ...
    @seek_infos.setter
    def seek_infos(self, arg1: collections.abc.Sequence[collections.abc.Sequence[StreamSeekInfo]]) -> None:
        ...
class Fstp(IAssetFile):
    data: PrefetchDataBlock
    endian: oead.Endianness
    info: StreamInfoBlock
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing_extensions.Buffer) -> None:
        ...
    @typing.overload
    def to_binary(self) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self, endian: oead.Endianness) -> oead.Bytes:
        ...
    @property
    def version(self) -> int:
        ...
    @version.setter
    def version(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Fwav(IAssetFile):
    encoding: SampleFormat
    endian: oead.Endianness
    is_loop: bool
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing_extensions.Buffer) -> None:
        ...
    def get_channel_info(self, channel: typing.SupportsInt | typing.SupportsIndex) -> ChannelInfo:
        ...
    def set_channel_info(self, info: ChannelInfo, channel: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def to_binary(self) -> oead.Bytes:
        ...
    @typing.overload
    def to_binary(self, endian: oead.Endianness) -> oead.Bytes:
        ...
    @property
    def channel_infos(self) -> list[ChannelInfo]:
        ...
    @channel_infos.setter
    def channel_infos(self, arg1: collections.abc.Sequence[ChannelInfo]) -> None:
        ...
    @property
    def loop_end_frame(self) -> int:
        ...
    @loop_end_frame.setter
    def loop_end_frame(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_start_frame(self) -> int:
        ...
    @loop_start_frame.setter
    def loop_start_frame(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def original_loop_start_frame(self) -> int:
        ...
    @original_loop_start_frame.setter
    def original_loop_start_frame(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sample_rate(self) -> int:
        ...
    @sample_rate.setter
    def sample_rate(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def samples(self) -> list[list[int | int | int | int]]:
        ...
    @samples.setter
    def samples(self, arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
class IAssetFile:
    pass
class MarkerInfo:
    name: str
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def length(self) -> int:
        ...
    @length.setter
    def length(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def start_pos(self) -> int:
        ...
    @start_pos.setter
    def start_pos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class PrefetchData:
    @property
    def prefetch_samples(self) -> oead.Bytes:
        ...
    @prefetch_samples.setter
    def prefetch_samples(self, value: oead.Bytes | bytes) -> None:
        ...
    def __init__(self) -> None:
        ...
    @property
    def start_frame(self) -> int:
        ...
    @start_frame.setter
    def start_frame(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class PrefetchDataBlock:
    def __init__(self) -> None:
        ...
    @property
    def prefetch_data(self) -> list[PrefetchData]:
        ...
    @prefetch_data.setter
    def prefetch_data(self, arg0: collections.abc.Sequence[PrefetchData]) -> None:
        ...
class SampleFormat:
    """
    Members:
    
      PCMS8
    
      PCMS16
    
      DSPADPCM
    
      PCMS32
    """
    DSPADPCM: typing.ClassVar[SampleFormat]  # value = <SampleFormat.DSPADPCM: 2>
    PCMS16: typing.ClassVar[SampleFormat]  # value = <SampleFormat.PCMS16: 1>
    PCMS32: typing.ClassVar[SampleFormat]  # value = <SampleFormat.PCMS32: 3>
    PCMS8: typing.ClassVar[SampleFormat]  # value = <SampleFormat.PCMS8: 0>
    __members__: typing.ClassVar[dict[str, SampleFormat]]  # value = {'PCMS8': <SampleFormat.PCMS8: 0>, 'PCMS16': <SampleFormat.PCMS16: 1>, 'DSPADPCM': <SampleFormat.DSPADPCM: 2>, 'PCMS32': <SampleFormat.PCMS32: 3>}
    @typing.overload
    def __eq__(self, other: SampleFormat) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: SampleFormat) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SoundFileHeader:
    @property
    def signature(self) -> typing.Annotated[list[str], "FixedSize(4)"]:
        ...
    @signature.setter
    def signature(self, arg0: typing.Annotated[collections.abc.Sequence[str], "FixedSize(4)"]) -> None:
        ...
    @property
    def version(self) -> int:
        ...
    @version.setter
    def version(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class StreamInfoBlock:
    stream_info: StreamSoundInfo
    def __init__(self) -> None:
        ...
    def get_channel_info(self, channel: typing.SupportsInt | typing.SupportsIndex) -> DspAdpcmInfo:
        ...
    def get_track_info(self, id: typing.SupportsInt | typing.SupportsIndex) -> StreamTrackInfo:
        ...
    def set_channel_info(self, info: DspAdpcmInfo, channel: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_track_info(self, info: StreamTrackInfo, id: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def channel_infos(self) -> list[DspAdpcmInfo]:
        ...
    @channel_infos.setter
    def channel_infos(self, arg1: collections.abc.Sequence[DspAdpcmInfo]) -> None:
        ...
    @property
    def track_infos(self) -> list[StreamTrackInfo]:
        ...
    @track_infos.setter
    def track_infos(self, arg1: collections.abc.Sequence[StreamTrackInfo]) -> None:
        ...
class StreamRegionInfo:
    is_enabled: bool
    def __init__(self) -> None:
        ...
    @property
    def adpcm_context(self) -> typing.Annotated[list[DspAdpcmLoopParam], "FixedSize(16)"]:
        ...
    @adpcm_context.setter
    def adpcm_context(self, arg0: typing.Annotated[collections.abc.Sequence[DspAdpcmLoopParam], "FixedSize(16)"]) -> None:
        ...
    @property
    def end(self) -> int:
        ...
    @end.setter
    def end(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def region_name(self) -> typing.Annotated[list[str], "FixedSize(64)"]:
        ...
    @region_name.setter
    def region_name(self, arg0: typing.Annotated[collections.abc.Sequence[str], "FixedSize(64)"]) -> None:
        ...
    @property
    def start(self) -> int:
        ...
    @start.setter
    def start(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class StreamSeekInfo:
    def __init__(self) -> None:
        ...
    @property
    def yn1(self) -> int:
        ...
    @yn1.setter
    def yn1(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def yn2(self) -> int:
        ...
    @yn2.setter
    def yn2(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class StreamSoundInfo:
    encoding: SampleFormat
    is_loop: bool
    def __init__(self) -> None:
        ...
    @property
    def block_count(self) -> int:
        ...
    @block_count.setter
    def block_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def block_sample_count(self) -> int:
        ...
    @block_sample_count.setter
    def block_sample_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def block_size(self) -> int:
        ...
    @block_size.setter
    def block_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def channel_count(self) -> int:
        ...
    @channel_count.setter
    def channel_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def frame_count(self) -> int:
        ...
    @frame_count.setter
    def frame_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_block_padding_size(self) -> int:
        ...
    @last_block_padding_size.setter
    def last_block_padding_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_block_sample_count(self) -> int:
        ...
    @last_block_sample_count.setter
    def last_block_sample_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_block_size(self) -> int:
        ...
    @last_block_size.setter
    def last_block_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_start(self) -> int:
        ...
    @loop_start.setter
    def loop_start(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def original_loop_end(self) -> int:
        ...
    @original_loop_end.setter
    def original_loop_end(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def original_loop_start(self) -> int:
        ...
    @original_loop_start.setter
    def original_loop_start(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def region_count(self) -> int:
        ...
    @region_count.setter
    def region_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def region_info_size(self) -> int:
        ...
    @region_info_size.setter
    def region_info_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sample_rate(self) -> int:
        ...
    @sample_rate.setter
    def sample_rate(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def seek_info_interval_samples(self) -> int:
        ...
    @seek_info_interval_samples.setter
    def seek_info_interval_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def size_of_seek_info_atom(self) -> int:
        ...
    @size_of_seek_info_atom.setter
    def size_of_seek_info_atom(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class StreamTrack:
    @property
    def channel_count(self) -> int:
        ...
    @channel_count.setter
    def channel_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def volume(self) -> float:
        ...
    @volume.setter
    def volume(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class StreamTrackInfo:
    def __init__(self) -> None:
        ...
    @property
    def flags(self) -> int:
        ...
    @flags.setter
    def flags(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def pan(self) -> int:
        ...
    @pan.setter
    def pan(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def span(self) -> int:
        ...
    @span.setter
    def span(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def volume(self) -> int:
        ...
    @volume.setter
    def volume(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class WaveInfo:
    encoding: SampleFormat
    is_loop: bool
    def __init__(self) -> None:
        ...
    @property
    def loop_end_frame(self) -> int:
        ...
    @loop_end_frame.setter
    def loop_end_frame(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loop_start_frame(self) -> int:
        ...
    @loop_start_frame.setter
    def loop_start_frame(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def original_loop_start_frame(self) -> int:
        ...
    @original_loop_start_frame.setter
    def original_loop_start_frame(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sample_rate(self) -> int:
        ...
    @sample_rate.setter
    def sample_rate(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
