name: release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Universal wheels error on Mac, so use macos-latest for arm, and an Intel runner for x64
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"
      CIBW_ARCHS: auto64
      CIBW_SKIP: cp31?t-*

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.1

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl


  upload_pypi:
    if: github.event_name == 'release'
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}

      - name: Trigger documentation build
        run: curl -X POST -d "branches=latest" -d "token=${{ secrets.RTD_TOKEN }}" https://readthedocs.org/api/v2/webhook/oead/112051/
